version: '3'

services:
  moodle:
    image: moodle-php-fpm
    build: ./images/moodle
    hostname: moodle
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - "db"
    volumes:
      - ./volumes/moodle:/var/moodle
  db:
    image: mysql:5.7
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD:MYSQL_ROOT_PASSWORD_VALUE
      - MYSQL_DATABASE:moodle
      - MYSQL_USER:moodleuser
      - MYSQL_PASSWORD:MYSQL_PASSWORD_VALUE
    ports:
      - '3306:3306'
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql
      - ./volumes/mysql-conf.d:/etc/mysql/mysql.conf.d
